In [10]:
import numpy as np
# Q-1 Use numpy to generate array of 25 random numbers sampled from a standard normal distribution
rand_num = np.random.normal(0,1,25)
print("25 random numbers from a standard normal distribution:")
print(rand_num)

25 random numbers from a standard normal distribution:
[-0.17799948  0.26636019 -0.47604764  1.51229547 -0.85330939 -0.43187395
  0.78790949  1.1131185  -0.19558536 -0.11099398  1.06447664 -0.17653787
  1.14032016 -0.80090871 -1.12175247  0.38267508  0.47324506  0.45263273
 -0.69593843 -0.84691301 -0.34201427 -0.77942628 -0.95366391  1.56847831
 -0.3303078 ]


In [3]:
# Q-2 Create a random vector of size 30 and find the mean value.
x = np.random.random(30)
x.mean()
print(x.mean())

0.4458464060770294


In [4]:
# Q3-Insert 1 to 100 numbers in a numpy array and reshape it to 10*10 matrix.
data1 = list(range(1, 101))
arr1 = np.array(data1)
arr1 = np.arange(1, 101).reshape(10, -1)
print(arr1)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [11]:
# Q4-Create a 10x10 array with random values and find the minimum and maximum values.
arr = np.random.random((10,10))
print("Original Array:")
print(arr) 
arrmin, arrmax = arr.min(), arr.max()
print("Minimum value:",arrmin)
print("maximum value:",arrmax)

Original Array:
[[9.32761906e-01 2.47483216e-01 1.99490499e-01 2.93459226e-01
  9.94479449e-01 1.56692444e-01 5.64506146e-01 4.88903857e-01
  9.51277183e-01 3.14475644e-01]
 [1.83858793e-01 5.79857490e-01 7.03631260e-01 6.70320120e-01
  2.63356639e-01 9.18077237e-01 5.68346615e-01 1.66235278e-01
  3.12255026e-01 7.40579925e-02]
 [5.88865591e-01 4.71696592e-01 6.67438517e-04 3.71230516e-01
  4.57877434e-02 6.68847575e-01 4.30683439e-01 1.51100687e-02
  4.09166861e-01 4.22307830e-01]
 [8.70713420e-01 4.79770703e-01 5.74159685e-01 2.00849198e-01
  7.26142251e-01 7.63106130e-01 3.28001743e-01 6.36676325e-01
  4.96094205e-01 3.75326380e-01]
 [6.79886855e-02 3.90831886e-01 9.34421273e-01 6.31671530e-01
  2.02863565e-01 6.04346737e-01 9.63753508e-01 5.29129310e-01
  6.65767000e-01 1.77968157e-01]
 [1.91373499e-02 5.43780471e-01 3.20958421e-02 8.40871403e-01
  8.83125298e-01 7.71038078e-01 9.59585052e-01 5.17892952e-01
  9.98376935e-02 2.92182402e-01]
 [7.77779297e-01 7.43572142e-01 5.82872123

In [6]:
# Q5-Find Dot product of two arrays
f = np.array([1,2])
g = np.array([4,5])
print(np.dot(f,g))

14


In [7]:
# Q6-Concatenate following arrays along axis=0
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])
print(np.concatenate((x, y), axis=0))

[[1 2]
 [3 4]
 [5 6]]


In [8]:
# Q7-How to get the common items between two python numpy arrays?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


In [12]:
# Q8-Sort the numpy array:
arr = np.array([10,5,8,4,7,2,3,1])
print(np.sort(arr))

[ 1  2  3  4  5  7  8 10]
